---
- name: Create {{ podman_group }} group
  ansible.builtin.group:
    name: "{{ podman_group }}"
    system: yes
  register: group

- name: Add ansible user to {{ podman_group }} group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: "{{ podman_group }}"
    append: yes
  notify: reset_connection

- name: Create {{ podman_user }} user
  ansible.builtin.user:
    name: "{{ podman_user }}"
    group: "{{ podman_group }}"
    shell: /bin/nologin
    system: yes
  register: user

- name: Add {{ podman_user }} user to systemd-journal group
  ansible.builtin.user:
    name: "{{ podman_user }}"
    groups: systemd-journal
    append: yes

- name: Set {{ podman_user }} user facts
  ansible.builtin.set_fact:
    podman_user_home: "{{ user.home }}"
    podman_user_uid: "{{ user.uid }}"
    podman_user_gid: "{{ group.gid }}"

- name: Create subuid using uid and bitwise shift left
  ansible.builtin.shell:
    cmd: "echo $(( {{ podman_user_uid }} << 16))"
  register: bit_shift_left

- name: Display output of {{ bit_shift_left }}
  ansible.builtin.debug:
    var: bit_shift_left.stdout

- name: Set {{ podman_user }} bit_shift_left fact
  ansible.builtin.set_fact:
    podman_user_uid_bit_shift_left: "{{ bit_shift_left.stdout }}"

# 2 to the power of 16 = 65536
# thats why subuid zones will not overlap each over

#cat /etc/subgid
#992:65208320:65536
#991:65142784:65536
# Have check corner case, is it overlapping or not? 
# I don't get it yet.
# 65208320 - 65536 = 65142784

- name: Add {{ podman_user }} user to subuid file
  ansible.builtin.lineinfile:
    path: /etc/subuid
    regexp: "^{{ podman_user_uid }}:.*"
    line: "{{ podman_user_uid }}:{{ podman_user_uid_bit_shift_left }}:65536"
    create: true
    mode: '0644'
    owner: root
    group: root

- name: Add {{ podman_group }} group to subgid file
  ansible.builtin.lineinfile:
    path: /etc/subgid
    regexp: "^{{ podman_user_gid }}:.*"
    line: "{{ podman_user_gid }}:{{ podman_user_uid_bit_shift_left }}:65536"
    create: true
    mode: '0644'
    owner: root
    group: root

- name: Check lingering for user {{ podman_user }}
  stat:
    path: "/var/lib/systemd/linger/{{ podman_user }}"
  register: user_lingering

# it is faster to check filepath than simple call loginctl 

- name: Enable lingering for {{ podman_user }} user
  command:
    cmd: "loginctl enable-linger {{ podman_user }}"
    creates: "/var/lib/systemd/linger/{{ podman_user }}"
  when: not user_lingering.stat.exists
  become: yes

- name: Flush handlers
  ansible.builtin.meta: flush_handlers