---
- name: Create {{ podman_group }} group
  ansible.builtin.group:
    name: "{{ podman_group }}"
    system: yes
  register: group

- name: Add ansible user to {{ podman_group }} group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: "{{ podman_group }}"
    append: yes
  notify: reset_connection

- name: Create {{ podman_user }} user
  ansible.builtin.user:
    name: "{{ podman_user }}"
    group: "{{ podman_group }}"
    shell: /bin/nologin
    system: yes
  register: user

- name: Add {{ podman_user }} user to systemd-journal group
  ansible.builtin.user:
    name: "{{ podman_user }}"
    groups: systemd-journal
    append: yes

- name: Find the largest subuid start number at /etc/subuid
  ansible.builtin.script: "gen_next_sub.py --filepath /etc/subuid --subcounts 65536"
  args:
    executable: python3
  register: next_sub_number

- name: Set {{ podman_user }} user facts
  ansible.builtin.set_fact:
    podman_user_uid: "{{ user.uid }}"
    podman_user_gid: "{{ group.gid }}"
    podman_user_uid_start_range: "{{ next_sub_number.stdout }}"

- name: Add {{ podman_user }} user to subuid file
  ansible.builtin.lineinfile:
    path: /etc/subuid
    regexp: "^{{ podman_user_uid }}:.*"
    line: "{{ podman_user }}:{{ podman_user_uid_start_range }}:{{ uid_gid_counts }}"
    create: true
    mode: '0644'
    owner: root
    group: root

- name: Add {{ podman_group }} group to subgid file
  ansible.builtin.lineinfile:
    path: /etc/subgid
    regexp: "^{{ podman_user_gid }}:.*"
    line: "{{ podman_user }}:{{ podman_user_uid_start_range }}:{{ uid_gid_counts }}"
    create: true
    mode: '0644'
    owner: root
    group: root

- name: Check lingering for user {{ podman_user }}
  stat:
    path: "/var/lib/systemd/linger/{{ podman_user }}"
  register: user_lingering
# it is faster to check filepath than simple call loginctl 

- name: Enable lingering for {{ podman_user }} user
  command:
    cmd: "loginctl enable-linger {{ podman_user }}"
    creates: "/var/lib/systemd/linger/{{ podman_user }}"
  when: not user_lingering.stat.exists
  become: yes

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
